packages:
  - packages/*
  - ./

linkWorkspacePackages: true

nodeLinker: hoisted

onlyBuiltDependencies:
  - core-js
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - win-screen-resolution

preferWorkspacePackages: true

publicHoistPattern:
  - '*'

ignoreWorkspaceRootCheck: true